# Generated by Django 6.0.3 on 2026-03-29 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
        ('users', '0003_add_producer_role'),
    ]

    operations = [
    ]
