# Generated by Django 6.0.3 on 2026-03-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='BkuUrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitki', models.CharField(max_length=255)),
                ('aktif_madde', models.CharField(blank=True, default='', max_length=255)),
                ('ruhsat_no', models.CharField(blank=True, default='', max_length=100)),
                ('urun_adi', models.CharField(max_length=255)),
                ('etken_madde', models.CharField(blank=True, default='', max_length=255)),
                ('firma', models.CharField(blank=True, default='', max_length=255)),
                ('doz', models.CharField(blank=True, default='', max_length=255)),
                ('zarali', models.CharField(blank=True, default='', max_length=255)),
                ('son_ilac_hasat', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['bitki', 'urun_adi'],
                'unique_together': {('ruhsat_no', 'bitki', 'zarali')},
            },
        ),
    ]
